name: Daniel Margheim
favicon: null
layout_spectrum: 0.19991
typography_spectrum: 0.27797
title: Daniel Margheim
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f47227'
    - '#c55d28'
    - '#fbdac9'
    - '#231f20'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
